### ISSUE TITLE
Docs link here

### ISSUE THREAD

**Issue by jasonlfunk** [cloudinary/bower-cloudinary-jquery#1]
The documentation on the cloudinary website links to the repo:
http://cloudinary.com/documentation/jquery_integration#getting_started_guide

**Comment by roeeba** [comment]
Hi @jasonlfunk, we apologise for the very late response. It looks like this link had been removed from the docs. 
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
